title: Mesa Math Club
email:
description: >- # Ignore newlines until next key
  San Diego Mesa College Math Club
baseurl: "mesa-mc/"
url: "mesa-mc/"
twitter_username:
github_username:

markdown: kramdown
plugins:
  - jekyll-feed

exclude:
